version: "3"
services:
    api:
        restart: unless-stopped
        build:
          context: .
        environment:
            - ConnectionStrings:local=Server=db,1433;Database=IB160244_test;User=sa;Password=MasterCoolOkPw53+;
        ports:
            - "52391:52391"
        depends_on:
            - db
        links:
            - db
        networks:
            - mynet

    db:
        restart: unless-stopped
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        environment:
            SA_PASSWORD: "MasterCoolOkPw53+"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Enterprise"
        ports:
            - 1403:1433
        networks:
            - mynet
networks:
  mynet:
    driver: bridge